name: Make Apk CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Author'
        required: false
        default: 'simplythebest'

jobs:
  Build-Apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Artifact naming
        run: |
          artifact="${{ github.repository_owner }} ${{ github.ref_name }}"
          artifact="${artifact//\//-}"
          echo "artifact=${artifact}" >> $GITHUB_ENV

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.artifact }} debug_apk"
          path: build/outputs/apk/debug/*.apk
